name: Sync Trojan Workers Pages Content

on:
  schedule:
    # 每天 UTC 时间 16:00 运行
    # 相当于北京时间 24:00 (东八区)
    # (16:00 UTC = 00:00 KST/JST = 00:00 SGT/HKT/CST)
    - cron: '0 16 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        path: ./current-repo # 将当前仓库克隆到 'current-repo' 目录下

    - name: Clone target repository
      uses: actions/checkout@v4
      with:
        repository: asfgrcv/Cloudflare_vless_trojan # 目标仓库
        ref: main # 目标分支
        path: ./target-repo # 将目标仓库克隆到 'target-repo' 目录下

    - name: Copy Trojan_workers_pages content
      run: |
        # 确保目标目录存在，如果不存在则创建
        mkdir -p ./current-repo/Trojan_workers_pages_Synced_Content # 您希望复制到的目标路径
        
        # 将目标仓库的指定子目录内容复制到当前仓库的指定目录
        # rsync 更高效，但如果不支持，可以使用 cp -R
        rsync -av --delete ./target-repo/Trojan_workers_pages/ ./current-repo/Trojan_workers_pages_Synced_Content/
        
        # 验证复制是否成功（可选）
        echo "Contents of the synced directory:"
        ls -la ./current-repo/Trojan_workers_pages_Synced_Content/

    - name: Configure Git for committing
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
      working-directory: ./current-repo # 在当前仓库目录下执行 git 配置

    - name: Commit and push changes
      run: |
        # 检查是否有更改，如果有则提交
        git add .
        git diff-index --quiet HEAD || git commit -m "Automated sync: Update Trojan_workers_pages content"
        git push
      working-directory: ./current-repo # 在当前仓库目录下执行 git 操作
