name: Sync Vless Workers Pages Content (Sparse Checkout Direct)

on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        path: ./

    - name: Prepare sparse checkout for target repository
      run: |
        mkdir ./target-repo_sparse
        cd ./target-repo_sparse
        git init
        git remote add origin https://github.com/yonggekkk/Cloudflare_vless_trojan.git
        git config core.sparseCheckout true
        echo "Vless_workers_pages/" >> .git/info/sparse-checkout
        git pull origin main

    - name: Copy Vless_workers_pages content to root
      run: |
        rsync -av --delete ./target-repo_sparse/Vless_workers_pages/ ./
        rm -rf ./target-repo_sparse/

    - name: Configure Git for committing
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push changes
      run: |
        git add .
        git diff-index --quiet HEAD || git commit -m "Automated sync: Update Vless_workers_pages content to root"
        git push
